UserMessages/Models/Message.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserMessages.Models
{
    public class Message
    {
        //одному сообщении соответствует только 1 пользователь
        //не может быть ситуации, когда для 1-го сообщения есть два пользователя - следовательно для сообщения есть связь 1 к 1
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public DateTime DateTime { get; set; }
        public string Text { get; set; }
        public int? UserId { get; set; }
        public User User { get; set; }
    }
}

UserMessages/Models/OnlinerForum.cs
namespace UserMessages.Models
{
    using System;
    using System.Data.Entity;
    using System.Linq;

    public class OnlinerForum : DbContext
    {       
        public OnlinerForum()
            : base("name=OnlinerForum")
        {
        }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    }
}

UserMessages/Models/ParseInfo.cs
using System.ComponentModel.DataAnnotations;
namespace UserMessages.Models
{
    public class ParseInfo
    {
        [Required(ErrorMessage = "Введите никнейм пользователя")]
        public string Name { set; get; }
        public int UserID { set; get; }
        [Required(ErrorMessage = "Введите макимальное количество сообщений для поимка")]
        [Range(1,5000,ErrorMessage ="Количество сообщений 1-5000")]
        public int MaxMessage { set; get; }
        [Required(ErrorMessage = "Введите количество просматриваемых страниц")]
        [Range(1,1000,ErrorMessage = "Количество страниц 1-1000")]
        public int PageCount { set; get; }
        [Required(ErrorMessage = "Введите адрес начальной страницы просмотра сообщений")]
        public string url { set; get; }
    }
}

UserMessages/Models/User.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserMessages.Models
{
    public class User
    {
        //Для таблицы пользователей организую связь одни ко многим
        //по логике 1 пользователь может иметь много сообщений
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public User()
        {
            Messages = new List<Message>();
        }
    }
}

UserMessages/Controllers/EnterDataController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using UserMessages.DBContext;
using UserMessages.Infrastructure;
using UserMessages.Infrastructure.Interfaces;
using UserMessages.Models;

namespace UserMessages.Controllers
{
    public class EnterDataController : Controller
    {
        private IHtmlParser parser;
        public EnterDataController(IHtmlParser htmlParser)
        {
            parser = htmlParser;
        }
        [HttpGet]
        public ActionResult UIEnter()
        {  
            return View();
        }
        [HttpPost]
        public ActionResult UIEnter(ParseInfo parseInfo)
        {
            using (OnlinerForum db = new OnlinerForum())
            {
                List<NodeOfParse> Notes = parser.ParseHtmlOnliner(parseInfo);
                List<Message> messages = new List<Message>();
                User user = new User();
                //db.Users.Load();                        
                user = db.Users.FirstOrDefaultAsync(u => u.Id == parseInfo.UserID || u.Name == parseInfo.Name).Result; //нахожу есть ли пользователь в базе                
                if (Notes.Count != 0)
                {
                    for (int currMsg = 0; currMsg < Notes.Count; currMsg++)
                    {
                        Message message = new Message()
                        {
                            Id = Notes[currMsg].IdMessage,
                            DateTime = Notes[currMsg].Date,
                            UserId = Notes[currMsg].UserId,
                            Text = Notes[currMsg].Message
                        };
                        messages.Add(message);
                    }
                    if (user == null) //нет БД Users
                    {
                        user = db.Users.Create();
                        user.Messages = new List<Message>(messages);
                        user.Id = Notes[0].UserId;
                        user.Name = parseInfo.Name;
                        db.Users.Add(user);
                    }
                    else
                    {
                        if (user.Id == 0) //нет пользователя
                        {
                            user.Messages = new List<Message>(messages);
                            user.Id = Notes[0].UserId;
                            user.Name = parseInfo.Name;
                            db.Users.Add(user);
                        }
                        else
                        {
                            foreach (var message in messages)
                            {
                                if (user.Messages.All(m => m.Id != message.Id))
                                {
                                    user.Messages.Add(message);
                                }
                            }
                            db.Users.Attach(user);
                        }
                    }                    
                    db.SaveChanges();
                }
            }        
            return View();
        }
    }
}

UserMessages/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserMessages.DBContext;
using UserMessages.Models;

namespace UserMessages.Controllers
{
    public class MessagesController : Controller
    {
        private OnlinerForum db = new OnlinerForum();

        // GET: Messages
        public ActionResult ViewBase()
        {
                var messages = db.Messages.Include(m => m.User);
                return View(messages.ToList());           
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserMessages/Views/EnterData/UIEnter.cshtml
@model UserMessages.Models.ParseInfo
@{
    ViewBag.Title = "UIEnter";
}
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h3>Введите данные для поиска</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.url, "Страница, с которой начать поиск(полный путь):", htmlAttributes: new { @class = "control-label col-md-5" } )
            <div class="col-md-7">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Ник пользователя, чьи сообщения искать:", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PageCount, "Количество просматриваемых страниц форума:", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-7">
                @Html.EditorFor(model => model.PageCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PageCount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MaxMessage, "Максимальное количество принимаемых сообщений:", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-7 tex">
                @Html.EditorFor(model => model.MaxMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxMessage, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Начать сканирование" class="btn btn-default"/>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

UserMessages/Views/Messages/ViewBase.cshtml
@model IEnumerable<UserMessages.Models.Message>

@{
    ViewBag.Title = "Index";
}

<h2>Просмотр данных</h2>

<table class="table table-striped ">
    <tr>
        <th>
            <span class="glyphicon glyphicon-user"></span>
            @Html.DisplayName("Автор")
        </th>
        <th>
            <span class="glyphicon glyphicon-calendar"></span>
            @Html.DisplayName("Дата")
        </th>
        <th>
            <span class="glyphicon glyphicon-envelope"></span>
            @Html.DisplayName("Сообщение")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(it => item.User.Name)
        </td>
        <td>
            @Html.DisplayFor(it => item.DateTime)
        </td>
        <td>
            @Html.Raw(item.Text)
        </td>        
    </tr>
}
</table>

UserMessages/Views/Messages/dbNotFound.cshtml
@{
    ViewBag.Title = "dbNotFound";
}

<h2>База данных не существует</h2>

UserMessages/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>*@
                @Html.ActionLink("Парсинг сообщений на форуме", "UIEnter", "EnterData", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Просмотр сообщений из БД", "ViewBase", "Messages", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - База сообщений пользователя Onliner.by</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>